### ISSUE TITLE
tests in Q9 are locale dependant

### ISSUE THREAD

**Issue by McFoggy** [forax/kata-restrospective-11#3]
Based on `java.util.Scanner`, tests in Q9 are `java.util.Locale` dependant.
On a _FR_fr_ jvm for example "100.5" (with dot) will not be parsed as a double by the scanner.

**Comment by forax** [comment]
Yes, i've forgotten that a Scanner instance is locale dependent :(

I think it's better to call useLocal(Locale.ROOT) on the Scanner than to use String.format().

**Comment by forax** [comment]
fixed by 0d585cd5e7c65b154699e99b3d1d1320fe8f1ffc

**Comment by McFoggy** [comment]
> I think it's better to call useLocal(Locale.ROOT) on the Scanner than to use String.format().

No problem ; I do no use that much Scanner and didn't checked it's API. 

> fixed by [0d585cd](https://github.com/forax/kata-restrospective-11/commit/0d585cd5e7c65b154699e99b3d1d1320fe8f1ffc)

Thanks.
