### ISSUE TITLE
wrong compilation errors reported in Intellij IDEA UI

### ISSUE THREAD

**Issue by McFoggy** [forax/kata-restrospective-11#5]
> This is not a defect/issue related to the project but a problem that people will probably face if they use Intellij IDEA. I wanted to report it so that others will not waste their time like I did struggling with Rémi's puzzle ;-)

Using latest Intellij IDEA version (`2018.3.4` as of today) errors are reported in tests for Q6 while probably your implementation of Lexer compiles fine using the CLI or maven.

![image](https://user-images.githubusercontent.com/1119660/52579537-a269fa00-2e26-11e9-973b-2f7ddf3ef9e9.png)

This is probably a bug in IDEA that has been reported as [IDEA-207070](https://youtrack.jetbrains.com/issue/IDEA-207070).

If you change the boot JDK of IDEA : `CTRL + SHIFT + A`, then 'Switch Boot JDK' and set a JDK11, then the compilation succeeds but... IDEA in a whole does not work anymore.

**Comment by forax** [comment]
Given the purpose of the kata is not to explain how the inference works/should work,
can you provide a patch that force the type of the List.of() to be a Function<String,Object> if it's a workaround for the IDEA bug ?

**Comment by McFoggy** [comment]
Yes forcing to `<Object>` corrects the _'compilation error'_. I'll submit a PR.
